name: Risk Forecast Agent

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  risk_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Risk Agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python agent/ingest_pr_diffs.py
          python agent/agent_runner.py